version: "3.8"

services:
  api_gateway:
    container_name: "api_gateway"
    build: .
    dns:
      - "172.20.0.5"
      - "8.8.8.8"
      - "8.8.8.4"
    ports:
      - "8080:8080"
      - "80:80"
      - "443:443"
    networks:
      consul-dc_mynet:
        ipv4_address: 172.20.0.9

networks:
  consul-dc_mynet:
    external: true